# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """\
[](bg:#030B16 fg:#7DF9AA)\
[󰀵 ](bg:#7DF9AA fg:#090c0c)\
[](fg:#7DF9AA bg:#1C3A5E)\
$time\
[](fg:#1C3A5E bg:#20B2AA)\
$directory\
$bun\
$deno\
$java\
$kotlin\
$rust\
$swift\
$zig\
[](fg:#20B2AA bg:#9370DB)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#9370DB bg:#030B16)\
$character\
"""

[directory]
format = "[  $path ]($style)"
style = "fg:#1C3A5E bg:#20B2AA"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#1C3A5E bg:#9370DB"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#9370DB"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#9370DB"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[ ❯](bold green) '
error_symbol = '[ ✗](#E84D44) '

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

# Languages

[bun]
format = "[| [$symbol($version )](bg:#20B2AA fg:#1C3A5E)]($style)"
style = "fg:#1C3A5E bg:#20B2AA"

[deno]
format = "[| [$symbol($version )](bg:#20B2AA fg:#1C3A5E)]($style)"
style = "fg:#1C3A5E bg:#20B2AA"

[java]
format = "[| [ ($version )](bg:#20B2AA fg:#1C3A5E)]($style)"
style = "fg:#1C3A5E bg:#20B2AA"

[kotlin]
format = "[| [ ($version )](bg:#20B2AA fg:#1C3A5E)]($style)"
style = "fg:#1C3A5E bg:#20B2AA"

[rust]
format = "[| [ ($version )](bg:#20B2AA fg:#1C3A5E)]($style)"
style = "fg:#1C3A5E bg:#20B2AA"

[swift]
format = "[| [ ($version )](bg:#20B2AA fg:#1C3A5E)]($style)"
style = "fg:#1C3A5E bg:#20B2AA"

[zig]
format = "[| [ ($version )](bg:#20B2AA fg:#1C3A5E)]($style)"
style = "fg:#1C3A5E bg:#20B2AA"
